version: '3'
services:
  directdemo:
    image: 'softwaremill/directdemo:latest'
    ports:
      - '8080:8080'
    depends_on:
      - directdemo-db
      - directdemo-mailhog
    environment:
      SQL_USERNAME: 'postgres'
      SQL_PASSWORD: 'b00t200k4'
      SQL_DBNAME: 'directdemo'
      SQL_HOST: 'directdemo-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
      SMTP_ENABLED: 'true'
      SMTP_HOST: 'directdemo-mailhog'
      SMTP_PORT: '1025'
  directdemo-db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'b00t200k4'
      POSTGRES_DB: 'directdemo'
  directdemo-mailhog:
    image: 'mailhog/mailhog'
    ports:
      - '11025:1025'
      - '18025:8025'

